#! /usr/bin/perl

# Generate an 'about' page for the StringHelp manual.
# The hash %about contains details of the manual which will be written
# to the about page in a standard way.
#
# Title : This is the title of the manual we're generating
# Description : A textual description for the manual
# Author : The author's name
# Email : The author's email address
# #.## (## ### ####) : A historical entry, expected to be read in ascending
#                      numerical order
# 
# Use &about_create("filename"); to create the page.

sub about_create
{
  local ($file) = @_;
  local ($history, $key, $current, $_);
  open(ABOUT, "> $file") || die;
  
  foreach $key (sort { $a cmp $b } %about)
  {
    if ($key =~ /(.\...) (\(.. ... ....\))/)
    {
      $current = $1;
      $_ = $about{$key};
      s/\n$//;
      s/\n/\n\t\t\t/g;
      $history .= "$key\t$_\n\n";
    }
  }
  
  $history =~ s/\n*$//;
  
  print ABOUT <<EOM;
${about{'Title'}}
#Align Centre
#fh3:${about{'Title'}} v${current}
#Align Left
${about{'Description'}}

If you have any suggestions for this manual, please mail ${about{'Author'}} \\<<${about{'Email'}}=>#URL mailto:${about{'Email'}}>\\>.

#fH4:History
$history
EOM
  close(ABOUT);
}

# Generate the text to go at the foot of a root page to link to the 'about'
# description
sub about_rootfooter
{
  local ($file, $program) = @_;
  local ($key, $current, $_);
  local ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst);
  local ($today);
  local (%months);
  
  foreach $key (sort { $a cmp $b } %about)
  {
    if ($key =~ /(.\...) (\(.. ... ....\))/)
    {
      $current = $key;
    }
  }
  ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) =
                                                localtime(time);
  %months = (
    0 => "Jan",
    1 => "Feb",
    2 => "Mar",
    3 => "Apr",
    4 => "May",
    5 => "Jun",
    6 => "Jul",
    7 => "Aug",
    8 => "Sep",
    9 => "Oct",
    10 => "Nov",
    11 => "Dec"
  );
  $year+=1900;
  $today = "$mday $months{$mon} $year";
  return <<EOM;
#Line
#align centre
${about{'Title'}}, created $today.
Automatically generated by <$program=>$file> {/}v${current}{/}. 
EOM
}

1;
